# Generated by Django 5.2.10 on 2026-01-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalskater',
            name='is_coach',
            field=models.BooleanField(default=False, verbose_name='Coach'),
        ),
        migrations.AddField(
            model_name='historicalskater',
            name='photo',
            field=models.TextField(blank=True, max_length=100, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='skater',
            name='is_coach',
            field=models.BooleanField(default=False, verbose_name='Coach'),
        ),
        migrations.AddField(
            model_name='skater',
            name='photo',
            field=models.ImageField(blank=True, upload_to='skaters/', verbose_name='Photo'),
        ),
    ]
