# Generated by Django 5.2.10 on 2026-01-12 17:17

from django.db import migrations




def migrate_booleans_to_tags(apps, schema_editor):
    Skater = apps.get_model("attendance", "Skater")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Tag = apps.get_model("taggit", "Tag")
    TaggedItem = apps.get_model("taggit", "TaggedItem")

    skater_content_type = ContentType.objects.get_for_model(Skater)

    active_tag, _ = Tag.objects.get_or_create(name="Active", slug="active")
    coach_tag, _ = Tag.objects.get_or_create(name="Coach", slug="coach")

    for skater in Skater.objects.all():
        if skater.is_active:
            TaggedItem.objects.get_or_create(
                tag=active_tag,
                content_type=skater_content_type,
                object_id=skater.id
            )
        if skater.is_coach:
            TaggedItem.objects.get_or_create(
                tag=coach_tag,
                content_type=skater_content_type,
                object_id=skater.id
            )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_skater_tags'),
    ]

    operations = [
        migrations.RunPython(migrate_booleans_to_tags),
    ]
