# Generated by Django 5.2.10 on 2026-01-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20260112_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalskater',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalskater',
            name='is_coach',
        ),
        migrations.RemoveField(
            model_name='skater',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='skater',
            name='is_coach',
        ),
    ]
