# Generated by Django 5.2.10 on 2026-01-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_historicalskater_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Reminder Sent'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Reminder Sent'),
        ),
    ]
