# Generated by Django 5.2.11 on 2026-02-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skaters', '0003_coach_alter_attendance_unique_together_skater_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='derby_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Derby Name'),
        ),
        migrations.AddField(
            model_name='coach',
            name='derby_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Derby Number'),
        ),
        migrations.AddField(
            model_name='skater',
            name='derby_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Derby Name'),
        ),
        migrations.AddField(
            model_name='skater',
            name='derby_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Derby Number'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Legal Name'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Legal Name'),
        ),
        migrations.AlterField(
            model_name='skater',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Legal Name'),
        ),
    ]
